### ISSUE TITLE
Images that were inserted via markdown are not lazyloaded

### ISSUE THREAD

**Issue by KOT-OPET** [gethyas/images#18]
## Description

Although[ Doks docs page for images](https://getdoks.org/docs/how-to/images-and-media/images/) clearly states that images are lazyloaded, turned out they are not.

### Steps to reproduce

One can see it by looking into the source code of the said docs page. The example of markdown-driven image with the following code...

`![Green Sea Turtle Hatchling by Hannah Le Leu](images/green-sea-turtle-hatchling.jpg)`

...produces this line of HTML:

```
<img class="img-fluid blur-up ls-is-cached lazyloaded" srcset="<<<list of sources>>>" width="2048" height="1366">
```

(I've deleted alt text for clarity)

However, **srcset** attribute doesn't work with lazysides module that handles lazyloading. It [requires](https://github.com/aFarkas/lazysizes#how-to) **data-srcset** attribute instead.

I've checked the loading of page sources. All 40 images from my test page loaded right away, without any "laziness".

### Expected result

Lazyloading of the images

### Actual result

Simultaneous loading of the images.

### Environment

```
{
  '@hyas/doks': '0.5.0',
  npm: '9.6.7',
  node: '20.3.1',
  acorn: '8.8.2',
  ada: '2.5.0',
  ares: '1.19.1',
  base64: '0.5.0',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.0',
  icu: '73.1',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.53.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.9+quic',
  simdutf: '3.2.12',
  tz: '2023c',
  undici: '5.22.1',
  unicode: '15.0',
  uv: '1.45.0',
  uvwasi: '0.0.18',
  v8: '11.3.244.8-node.9',
  zlib: '1.2.13.1-motley'
}

> @hyas/doks@0.5.0 check
> exec-bin node_modules/.bin/hugo/hugo version

hugo v0.107.0-2221b5b30a285d01220a26a82305906ad3291880+extended darwin/amd64 BuildDate=2022-11-24T13:59:45Z VendorInfo=gohugoio
```

**Comment by h-enk** [comment]
Images 3.0 now is way more robust — and I dropped [aFarkas/lazysizes](https://github.com/aFarkas/lazysizes) support, for [no longer really that relevant](https://cloudinary.com/blog/cloudinary-lqip-and-lazy-loading-best-practices)

You should now see consistent and correct working behavior

**Comment by KOT-OPET** [comment]
Thank you!

I'm still on Doks 0.5 though, and I'd prefer not to update the main theme, because I've modified it _a lot_ for my project, and I presume there would be a ton of compatibility issues if I'd update it.

Is there an easy way to implement a new image module to Doks 0.5?

Also, how do you handle LQIP now? Is it still some JS module?

**Comment by h-enk** [comment]
Upgrading to Doks v1 should not be that hard — also in your case. Here's the [Upgrade to v1](https://getdoks.org/docs/start-here/upgrade-to-v1/) guide if you'd like to give it a try.

Looks like you could just [upgrade](http://localhost:1313/docs/start-here/getting-started/#updating-images) easily — this should update [@hyas/images](https://github.com/gethyas/doks/blob/v0.5.0/package.json#L45 ) from `0.2.1` to `3.0.0`. Also check the [Manual Setup](https://images.gethyas.com/docs/start-here/manual-setup/) guide for updating configuration settings.

LQIP now is not that relevant anymore — so I dropped support for it. Read more on that here for example: [Browser-level image lazy loading for the web](https://web.dev/articles/browser-level-image-lazy-loading)

**Comment by KOT-OPET** [comment]
Thanks, maybe in the future. I have a lot of custom scss, and also I've modified image handling in a last couple of months. I'm pretty happy with the way it is in my build now.

Probably I'll start another project after I'll finish this one, and then I'll give the new doks version a try.
