### ISSUE TITLE
Support for caption in image using a separate shortcode

### ISSUE THREAD

**Issue by adhadse** [gethyas/images#8]
The current Goldmark markdown for image don't support `figcaption`, and so markdown rendered hook for it also won't support any figcaption as Hugo won't provide it.

Can we have a `figure` shortcode that can do lazysizes blurry loading and support providing captions via `caption` parameter?

Also, support of `gif` and `svg` might be required.

**Comment by h-enk** [comment]
Images 3.0 now supports this — see for example https://images.gethyas.com/docs/shortcodes/figure/

You can now also add `gif` images to your `.md` pages by using the Markdown syntax for images — see https://images.gethyas.com/docs/built-ins/gif/

You can add `svg` using [Hyas inline SVG](https://github.com/gethyas/inline-svg)
